export const EXCLUIR_PROJETO = "EXCLUIR_PROJETO";
export const LISTAR_PROJETOS = "LISTAR_PROJETOS";

export const NOTIFICAR = "NOTIFICAR";

export const EXCLUIR_TAREFA = "EXCLUIR_TAREFA";
export const LISTAR_TAREFAS = "LISTAR_TAREFAS";
